# 导入颜色文件
include themes/mocha.conf
# 设置左右边距
window_padding_width 5
# 隐藏标题栏
hide_window_decorations yes
# 背景透明度
background_opacity 0.5
# 字体
font_family Adwaita Mono
# 字体大小
font_size 13
# 不要记住窗口大小（yes no）
remember_window_size no
# 关闭窗口时不要询问是否关闭
confirm_os_window_close 0
# 设置默认的 shell 为 zsh
shell /usr/bin/zsh
# 添加光标动画
cursor_trail 3 
